// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM7L-zb82vaON0F7hGKKwd9BdqcAzGEj4',
    appId: '1:329212908307:android:40d6fbe8f0d987d5db80e6',
    messagingSenderId: '329212908307',
    projectId: 'roaah-alhamoud',
    databaseURL: 'https://roaah-alhamoud-default-rtdb.firebaseio.com',
    storageBucket: 'roaah-alhamoud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBskFek3wDAv182kagGElIjTWvdf-GhMQ8',
    appId: '1:329212908307:ios:7e81d5665c12ca9adb80e6',
    messagingSenderId: '329212908307',
    projectId: 'roaah-alhamoud',
    databaseURL: 'https://roaah-alhamoud-default-rtdb.firebaseio.com',
    storageBucket: 'roaah-alhamoud.appspot.com',
    iosBundleId: 'com.example.flutterGpsDeviceTrackingApp',
  );
}
